### PR TITLE
I18n code review

### PR DESCRIPTION
**Pull request by G3ronim0**
Hi,
I just finished a i18n code review for Conditional Logic.
Best regards

### CODE REVIEW

**Comment by mgibbs189** [comment]
@G3ronim0 thanks for the PR, looks great! I did have a few minor suggestions:

1. It'd be better to wrap the translations within a`FWPCL.__()` function, instead of using `FWPCL.i18n` directly. E.g. before:

```js
FWPCL.i18n.changes_saved
```

and after:

```js
FWPCL.__('Changes saved')
```

Using the actual string (e.g. `Changes saved` vs `changes_saved`) would be ideal here, even if it's a bit more verbose. The function would prevent errors if a string isn't available.

Here's how the `__()` function looks in FacetWP core:

```js
window.FWP.__: function(str) {
        return ('undefined' !== typeof FWP.i18n[str]) ? FWP.i18n[str] : str;
};
```

**Comment by G3ronim0** [comment]
Thanks for the quick response. I just made a commit, is that the idea? https://github.com/FacetWP/facetwp-conditional-logic/pull/27/commits/3b9371a0fabdae64bf33ba0bcf6b8dc983fa5028

**Comment by mgibbs189** [comment]
Almost! here's another example:

```js
if (confirm(FWPCL.__('delete_ruleset'))) {
```

should be:

```js
if (confirm(FWPCL.__('Delete this ruleset?'))) {
```

and then the `admin_i18n` line should change from:

```php
'delete_ruleset' => __( 'Delete this ruleset?' , 'facetwp-conditional-logic' ),
```

to

```php
'Delete this ruleset?' => __( 'Delete this ruleset?' , 'facetwp-conditional-logic' ),
```

So with the above, the array key should match the string being translated. Does that make sense?

With the translations using this approach instead, the fallback strings will be the "real" English defaults. Thanks again for all your work on this thus far!

**Comment by G3ronim0** [comment]
Ok, I think I'm good. Tell me https://github.com/FacetWP/facetwp-conditional-logic/pull/27/commits/9f9e213e4e43530ed934d8ff9e34feca91d4c095

**Comment by mgibbs189** [comment]
@G3ronim0 Everything looks great, merged 👍 🎉

**Comment by G3ronim0** [comment]
Thanks ;-)

**Pull request merged**
